### ISSUE TITLE
Upgradeable or Bonus Effect cards not working properly.

### ISSUE THREAD

**Issue by connordmccandless** [djdookie/Advisor#19]
If someone plays a "Greater Amethyst Spellstone" or a "Purifier's Maul", the plugin doesn't recognize that these are the same cards as "Lesser Amethyst Spellstone" or "Unidentified Maul" in terms of decklist.

**Comment by djdookie** [comment]
As Advisor completely relies on the opponent's cardlist tracked by Hearthstone Deck Tracker, this has to be recognized there. There is no extra card intelligence in this addon. So please post that issue here https://github.com/HearthSim/Hearthstone-Deck-Tracker/issues
