### ISSUE TITLE
Request for scaling and opacity settings (feature request)

### ISSUE THREAD

**Issue by chWolfgang** [djdookie/Advisor#2]
First, thank you for this mod. It is something I have been looking for.
I would like to request the ability to scale your plugin. I run about 70 for most of HDT.
Also, being to adjust the opacity would be helpful.

Thanks again for your time.
chWolfgang

**Comment by chWolfgang** [comment]
Now that I am thinking about it a bit more, I have another idea. This may be way more work that it is worth but, would it be possible to make a mode that would just show that name of deck and percentage and then - on mouse over - show the rest of the deck list? 

TL:DR; Request: turn deck list opacity from 0 to 100 during mouse over of deck name/percentage.

chWolfgang

**Comment by djdookie** [comment]
Hi @chWolfgang,
thanks for your feedback and your ideas.
Scaling is a feature I already planned for a future release.
Opacity and mouse over deck name/percentage sounds interesting related to the low available space on screen.
I will have a look into how much effort this would need to be implemented.

**Comment by djdookie** [comment]
Overlay scaling and opacity is implemented with 13564b5e7692b068f83f7439353f3a8a12c708fc
