### ISSUE TITLE
Any chance for an update/release of finished work?

### ISSUE THREAD

**Issue by chWolfgang** [djdookie/Advisor#23]
Is any chance we can get a release of the work already done? This is such a useful add-on with a couple things that could use updating. Thanks for all efforts put into this.

**Comment by djdookie** [comment]
Hi. Thanks for your commendation, and sorry for the late reply.
Unfortunately, since I don't play Hearthstone anymore and I don't find the free time for any further development I regard Advisor as feature complete.
Feel free to improve it and make a pull request yourself!
