### ISSUE TITLE
Make threshold for similarity value configurable

### ISSUE THREAD

**Issue by djdookie** [djdookie/Advisor#6]
Currently an archetype deck is shown after at least one deck's similarity is higher than a specific threshold.
This is >0% at the moment. If multiple decks have the same highest similarity value, one of them is randomly selected (should depend on the import order).

We could make that threshold configurable.
Additionally we could show an archetype deck not before there is only one deck with a highest similarity.
This should be a good complement to #3.

**Comment by BernsteinA** [comment]
I've opened a Pull Request #15 which adds this feature

**Comment by djdookie** [comment]
Thanks for your work @BernsteinA.
This feature was recently released with v1.0.6 https://github.com/djdookie/Advisor/commit/be912438db5ea24f6dbe505d78c5e71c96e76137
