### ISSUE TITLE
there is no import arcatype button anywhere you said it was.

### ISSUE THREAD

**Issue by thegreatloki** [djdookie/Advisor#7]
what title says,  please help fast

**Comment by thegreatloki** [comment]
![hsdtadvisornotworking](https://cloud.githubusercontent.com/assets/25728314/22865777/c2c6e6fa-f138-11e6-8f7e-27234c72ff2d.png)

**Comment by thegreatloki** [comment]
ok sorry,  i figured it out.  its not in options haha

**Comment by djdookie** [comment]
Yeah it's in the menu toolbar. Good that you found it! Cheers.
