### ISSUE TITLE
Manually import decks

### ISSUE THREAD

**Issue by judge2020** [djdookie/Advisor#9]
It would be useful to manually import decks, either from a site like Hearthpwn or getting the deck directly out of HDT.

Method for getting selected deck:
```C#
private static Deck _selectedDeck;
OnLoad() 
{
    Hearthstone_Deck_Tracker.API.DeckManagerEvents.OnDeckSelected.Add(DeckSelected);
}
private static void DeckSelected(Deck deck)
{
_selectedDeck = deck;
}
```
deck is Hearthstone_Deck_Tracker.Hearthstone.Deck i believe.

**Comment by djdookie** [comment]
Hi @judge2020,
every HDT deck tagged with "Archetype" will be used for matching.
So you can simply use HDT's versatile (manual) import function to get decks from any supported website and tag the imported deck by yourself.
I guess this makes your request obsolete, right?
